name: Update README Stats Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=Philtait&show_icons=true&bg_color=0f0c29&title_color=67e8f9&icon_color=67e8f9&text_color=ffffff&hide_border=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=Philtait&layout=compact&bg_color=0f0c29&title_color=67e8f9&text_color=ffffff&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
